name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing GitHub Actions
on:
  push:
    branches:
      - main
env: 
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: run away
        run: cargo run
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run
        run: cargo run